// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0dra3FcdTYKZmXrMBjfGufS-qrzuY7bE',
    appId: '1:196155612800:web:a6313a2dd65402563f1065',
    messagingSenderId: '196155612800',
    projectId: 'appnghenhacdb',
    authDomain: 'appnghenhacdb.firebaseapp.com',
    storageBucket: 'appnghenhacdb.firebasestorage.app',
    measurementId: 'G-Y50TFLXJK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEvTPrZtTJMav3qi2uuPftzg7C8B7BLjk',
    appId: '1:196155612800:android:dfb6382a1f1c60bd3f1065',
    messagingSenderId: '196155612800',
    projectId: 'appnghenhacdb',
    storageBucket: 'appnghenhacdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyn834jsn36yFHvW3z85QNklf4_RDxHIg',
    appId: '1:196155612800:ios:d9c8d3b73021f59b3f1065',
    messagingSenderId: '196155612800',
    projectId: 'appnghenhacdb',
    storageBucket: 'appnghenhacdb.firebasestorage.app',
    iosBundleId: 'com.example.appNgheNhac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyn834jsn36yFHvW3z85QNklf4_RDxHIg',
    appId: '1:196155612800:ios:d9c8d3b73021f59b3f1065',
    messagingSenderId: '196155612800',
    projectId: 'appnghenhacdb',
    storageBucket: 'appnghenhacdb.firebasestorage.app',
    iosBundleId: 'com.example.appNgheNhac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0dra3FcdTYKZmXrMBjfGufS-qrzuY7bE',
    appId: '1:196155612800:web:0c598f94d312ef213f1065',
    messagingSenderId: '196155612800',
    projectId: 'appnghenhacdb',
    authDomain: 'appnghenhacdb.firebaseapp.com',
    storageBucket: 'appnghenhacdb.firebasestorage.app',
    measurementId: 'G-CRSZRWGXZX',
  );
}
