name: app_nghe_nhac
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  audiotagger: ^2.1.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  flutter_slidable: ^3.0.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.4
  flutter_media_metadata: ^1.0.0
  path_provider_android: ^2.1.2
  path_provider_ios: ^2.0.11
  path_provider_macos: ^2.0.7
  path_provider_windows: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/song/
    - assets/image/

